language: d
d:
 - dmd
 - ldc
script:
 - N=0; while : ; do M=`find . -not -regex .*\.dub/dub.json -a -name dub.json | while read F; do cat $F | perl -ne 'print if s/.*\"(deadcode-.*)\"\s*?:.*/\1/' ; done | sort | uniq | tee deps.txt | wc -l`; echo "$N $M"; [[ $N -eq $M ]] && break; N=$M; cat deps.txt; done
 - dub test -b unittest-cov --compiler=${DC}
after_success:
 - bash <(curl -s https://codecov.io/bash)
